steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/github.com/patatoa/$PROJECT_ID:$COMMIT_SHA", "./lofiget"]
    env:
      - "PROJECT_ID=lofiget"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/github.com/patatoa/$PROJECT_ID:$COMMIT_SHA"]
    env:
      - "PROJECT_ID=lofiget"

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "lofiget-staging", "--image", "gcr.io/$PROJECT_ID/github.com/patatoa/$PROJECT_ID:$COMMIT_SHA", "--platform", "managed", "--region", "us-central1"]
    env:
      - "PROJECT_ID=lofiget"